default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: littleshopprivatestache_development

test:
  <<: *default
  database: littleshopprivatestache_test

production:
  <<: *default
  database: littleshopprivatestache_production
  password: <%= ENV['LITTLESHOPPRIVATESTACHE_DATABASE_PASSWORD'] %>
